#!/bin/bash
##################
# devo.ps backup collection
##################
# Description:
#  CouchDB backup approach is simply to copy the files (when on a single server)
##################

SELF=$(basename -s .sh $0)
SERVICE=${SELF#backup-}

# Data available from ENV
DEST=$DEVOPS_BACKUP_DEST

# 
CONF_FOLDER=/opt/devops/backup/conf
CONF_FILE=$CONF_FOLDER/$SELF.conf

# Load main backup config file
if [ ! -e "$CONF_FOLDER/backup.conf" ]; then
    echo "Missing main backup config file" >&2
    exit 1
else
    . "$CONF_FOLDER/backup.conf"
fi

# Load script specific config file
if [ ! -e "$CONF_FILE" ]; then
    echo "Missing $SELF backup config file" >&2
    exit 1
else
    . "$CONF_FILE"
fi

# Prepare destination folder
DEST_FOLDER=$DEST/couchdb
mkdir -p $DEST_FOLDER

# CouchDB simply require to copy the files
echo "Start $SERVICE data backup"
cd $COUCHDB_DATA_DIR
tar czf $DEST_FOLDER/couchdb_data.tar.gz .
echo "Completed $SERVICE data backup"

echo "Start $SERVICE log backup"
cd $COUCHDB_LOG_DIR
tar czf $DEST_FOLDER/couchdb_log.tar.gz .
echo "Completed $SERVICE log backup"

echo "Start $SERVICE conf backup"
cd $COUCHDB_CONF_DIR
tar czf $DEST_FOLDER/couchdb_conf.tar.gz .
echo "Completed $SERVICE conf backup"
